(require 'corfu)
(setq corfu-auto t)
(setq corfu-quit-at-boundary t)
(setq corfu-auto-delay 0)
(setq corfu-auto-prefix 1)
(setq completion-styles '(orderless-fast basic))
(unless (display-graphic-p)
  (corfu-terminal-mode +1))
(global-corfu-mode)
(add-hook 'prog-mode-hook 'eglot-ensure)
